services:
  fastapi:
    build: .
    container_name: pdf_parsers
    deploy:
      resources:
        limits:
          memory: 12g
        reservations:
          memory: 8g         
    mem_limit: 12g          
    memswap_limit: 24g 
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY_1=${GEMINI_API_KEY_1}
      - GEMINI_API_KEY_2=${GEMINI_API_KEY_2}
      - GEMINI_API_KEY_3=${GEMINI_API_KEY_3}
      - GEMINI_API_KEY_4=${GEMINI_API_KEY_4}
    ports:
      - "8000:8000"
