services:
  fastapi:
    build: .
    container_name: pdf_parsers
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
